name: Build

on:
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Run hugo
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        git config --global user.email "ambhore.pranav@gmail.com"
        git config --global user.name "Hugo Blog"
        git status
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        git submodule update --init --recursive
        sudo snap install hugo
        hugo
