name: Build

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout blog with submodules
      uses: actions/checkout@v2
      with:
        ssh-key: '${{ secrets.SSH_PRIVATE_KEY }}'
        submodules: 'true'
    - name: Run hugo
      run: |
        git status
        sudo snap install hugo
        hugo -D
        ls public/blog
