name: Build

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Run hugo
    - uses: actions/checkout@v2
      with:
        ssh-key: '${{ secrets.SSH_PRIVATE_KEY }}'
        submodules: 'true'
    - run: |
        git config --global user.email "ambhore.pranav@gmail.com"
        git config --global user.name "Hugo Blog"
        git status
        sudo snap install hugo
        hugo -D
        ls public/blog
