name: Deploy

on:
  push:
    branches:
      - test_logs
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

    - name: Checkout blog with submodules
      uses: actions/checkout@v2
      with:
        ssh-key: '${{ secrets.SSH_PRIVATE_KEY }}'
        submodules: 'recursive'
    
    - name: Run hugo
      run: |
        git status
        sudo snap install hugo
        hugo -D
        ls public/blog

    - name: Run hugo
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        git config --global user.email "ambhore.pranav@gmail.com"
        git config --global user.name "Hugo Blog"
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        hugo
        cd public
        ls -al
        git status
        git init
        git add .
        # dt=$(date "+%H:%M:%S %d/%m/%y")
        # echo `git commit -m "CI done $dt"`
        git remote add origin git@github.com:pranav93/pranav93.github.io.git
        git push origin master -f
