name: CI

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Run hugo
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        git config --global user.email "ambhore.pranav@gmail.com"
        git config --global user.name "Hugo Blog"
        git status
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        git submodule update --init --recursive
        cd public
        git checkout master
        cd ..
        sudo snap install hugo
        hugo
        cd public
        git add .
        dt=date "+%H:%M:%S %d/%m/%y"
        git commit -m "CI done $dt"
        git push origin master -f
